# Generated by Django 5.2.4 on 2025-07-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='password',
            field=models.CharField(default='temp1234', max_length=100),
        ),
    ]
