# Generated by Django 5.2.4 on 2025-07-12 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurplusFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('attendees', models.PositiveIntegerField()),
                ('menu_type', models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg'), ('mixed', 'Mixed')], max_length=50)),
                ('prepared_quantity', models.FloatField(help_text='in kg')),
                ('predicted_surplus', models.FloatField(blank=True, help_text='AI will predict this', null=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
