# Generated by Django 5.2.4 on 2025-07-12 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusfood',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
