# Generated by Django 5.2.4 on 2026-05-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_surplusfood_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(default='temp1234', max_length=100),
        ),
    ]
